### ISSUE TITLE
2d[discuss] 组内协作流程规则

### ISSUE THREAD

**Issue by Hansoluo** [GC4WP/Sword-Stars#2]
## 背景
- 目前组队完毕，为保证成员按时完成作业和高效协作，需要满足以下要求：
    + 为了保证小组成员都充分参与作业，需要设计合作模式；
    + 为了尽可能减少沟通不畅，需要设计沟通方案；
    + 为了保留作业修改完善的痕迹，需要设计存档方案；
    + 尽可能节省时间和精力。

- 群里已有一期学员大妈和猛犸提供了非常成功的合作案例。其大体方案基本如下：
    + GitHub  仓库作为提交作业和点评作业的保存工具
    + GitHub Issues 作为准则存档、工作过程记录、任务分配、待办事项列表及主要沟通工具；
    + 邮件列表作为微信群聊天记录列表、GitHub Issues 的推送工具；
    + 微信小群作为讨论要点记录、日常沟通工具；
    + Zoom作为语音会议、共享屏幕推送工具。

> 参考资料：[GitHub 等协同写作工具说明](https://github.com/GC4WP/S07E15G89/issues/2)

- 目前需要做的尽快建立具体的协同规则，需要各小组成员一起讨论确定~~

### 提交作业

- 王老师在每周五授课完毕后会发布作业
- 各成员**最迟 周日 2200前**在 Code 中提交一版个人作业
- 文件名命名格式为 学号作业目录_版本号_提交时间.md（举例：069L01E01_V1_20171207.md）
- 文件名使用英文和数字，不要使用中文

### 点评作业

- 使用作业里自带的comment模式，各小组成员完成对其他成员作业的点评
-  时间：**最迟 周二 2200前**

### 回复及修改

- 成员回复他人的评论意见，选择修改或不修改，并提交修改后的作业版本
- 时间：**最迟 周四 1800前**

### 总结分享

- 召开zoom视频会议，每人分享这周作业的问题和心得
- 时间：**周四 2000~2130**
- 轮流主持会议及撰写会议小结

## 记录
~ 原始数据/过程/现象/...收集
- [基于 Issue 写作协同](https://github.com/GC4WP/common/issues/19)
- [GitHub 等协同写作工具说明](https://github.com/GC4WP/S07E15G89/issues/2)
- [[规约]组内协同规则](https://github.com/GC4WP/S07E15G89/issues/1)

## 变更
~ 记录合并大家 建议/增补/.. 来的主要变动信息

- 171207 醉舟 init.
- ... 使用日期 作者 记要 <-- 这种行格式来嗯哼

参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by xerinxie** [comment]
同意

**Comment by huanxi007** [comment]
严重同意，跟上组长步伐。

**Comment by jacobspf** [comment]
同意

**Comment by zhengzhengjingjing** [comment]
同意

**Comment by Hansoluo** [comment]
好的，目前大家都没问题，关闭issue
